spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: b1397b7367384595827c069ff2b73714
            client-secret: e2eb3f981eaa4a80b1454862d6d71c48
            scope:
              - user-read-email
              - user-read-private
            client-name: Spotify
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
